
public enum LEVEL_STATUS {NORMAL, PATTERN, END}

public enum PLAYER_ID {NORMAL, SPREAD, LASER, HOMING, BOOM,END};

public enum ENEMY_ID {NORMAL_S, NORMAL_M,SPEED, SPLIT_S, SPLIT_M, CHILD, FOLLOW_S, MOVE_S, IMM, COIN_S, COIN_M,END}

public enum BULLET_ID {LV1, LV2, LV3, LV4, END};

public enum MAINMENU_STATE {MAIN,OPTION,SHOP,CHARGE};

public enum ENEMY_SIZE {SMALL, MID};


//unityads
public enum ADSPLAY_STATE {SKIP, COMPLE};